// @ts-nocheck
import { Plugin } from 'vite'
import fg from 'fast-glob'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { resolve, relative, dirname } from 'path' // Removed unused 'join'

export interface BunSingleOptions {
  distDir?: string
  outDir?: string // Added outDir option
  assetsFile?: string // Renamed from outFile
  generateServer?: boolean
  serverFile?: string
}

export default function bunSingle(opts: BunSingleOptions = {}): Plugin {
  const distDir    = opts.distDir    || 'dist'
  const outDir     = resolve(opts.outDir || 'out') // Define outDir
  const assetsFile = resolve(outDir, opts.assetsFile || 'assets.generated.ts')
  const serverFile = resolve(outDir, opts.serverFile || 'server.ts')

  return {
    name: 'vite-plugin-bun-single',
    apply: 'build',
    async closeBundle() {
      // Ensure outDir exists
      if (!existsSync(outDir)) {
        mkdirSync(outDir, { recursive: true });
        console.log(`[bun-single] created output directory: ${outDir}`);
      }

      // 1) collect all your dist files
      const files = fg.sync(
        `${distDir}/**/*.{js,css,html,svg,png,jpg,json,woff2}`,
        { dot: true }
      )

      // 2) emit assets.generated.ts
      const lines = files.map(f => {
        // Ensure consistent path separators for the route key
        const route = '/' + relative(distDir, f).replace(/\\/g, '/'); // Corrected path separator replacement
        // Use absolute path for Bun.file for reliability, escape backslashes for the string literal
        const absoluteFilePath = resolve(f).replace(/\\/g, '\\'); // Corrected path separator replacement and escaping
        return `assets.set("${route}", await Bun.file("${absoluteFilePath}").arrayBuffer())`;
      }).join('\n');

      const code =
`// GENERATED by vite-plugin-bun-single

export const assets = new Map<string, ArrayBuffer>()
async function loadAssets() {
${lines}
}
await loadAssets()
`;
      writeFileSync(assetsFile, code)
      console.log('[bun-single] wrote ' + assetsFile)

      // 3) scaffold server.ts if wanted
      if (opts.generateServer && !existsSync(serverFile)) {
        // Adjust relative path calculation based on the new serverFile location
        const relAssetsPath = relative(dirname(serverFile), assetsFile).replace(/\\/g, '/'); // Corrected path separator replacement
        const srv =
`import { assets } from "./${relAssetsPath}"
import { fileTypeFromBuffer } from 'file-type';
import mime from "mime";

Bun.serve({
  port: Number(process.env.PORT) || 3000,
  async fetch(req) {
    let path = new URL(req.url).pathname
    if (path === "/") path = "/index.html"
    const buf = assets.get(path) ?? assets.get("/index.html");
    if (!buf) {
        return new Response("Not Found", { status: 404 });
    }
    const buffer = Buffer.from(buf);
    const fileTypeInfo = await fileTypeFromBuffer(buffer);
    const mimeType =
      fileTypeInfo?.mime ||
      mime.getType(path) ||
      "application/octet-stream"

    return new Response(buffer, {
      headers: {
        "content-type": mimeType,
        "content-length": buffer.byteLength.toString(),
        "cache-control": "public, max-age=31536000, immutable"
      }
    })
  }
})
`;
        writeFileSync(serverFile, srv)
        console.log('[bun-single] scaffolded ' + serverFile)
      }
    }
  }
}
